name: build-and-push

on:
  workflow_dispatch:

jobs:
  build-and-push-to-fit2cloud-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Prepare
        id: prepare
        run: |
          TAG_NAME=8.5.24
          DOCKER_IMAGE_TAGS="--tag ${{ secrets.DOCKER_IMAGE }}:${TAG_NAME}"
          echo ::set-output name=buildx_args::--platform linux/amd64 ${DOCKER_IMAGE_TAGS}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker Buildx (build-and-push)
        run: |
          docker buildx build --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }} .
